parameters:
    ezsettings.global.system_info_view:
        pjax_tab:
            composer:
                template: 'EzPlatformAdminUiBundle:admin/systeminfo:composer.html.twig'
                match:
                    SystemInfo\Identifier: 'composer'
            database:
                template: 'EzPlatformAdminUiBundle:admin/systeminfo:database.html.twig'
                match:
                    SystemInfo\Identifier: 'database'
            hardware:
                template: 'EzPlatformAdminUiBundle:admin/systeminfo:hardware.html.twig'
                match:
                    SystemInfo\Identifier: 'hardware'
            php:
                template: 'EzPlatformAdminUiBundle:admin/systeminfo:php.html.twig'
                match:
                    SystemInfo\Identifier: 'php'
            symfony_kernel:
                template: 'EzPlatformAdminUiBundle:admin/systeminfo:symfony_kernel.html.twig'
                match:
                    SystemInfo\Identifier: 'symfony_kernel'
