services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EzPlatformAdminUiBundle\Templating\Twig\UiConfigExtension: ~
    EzPlatformAdminUi\UI\Config\Aggregator: ~
