services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzPlatformAdminUiBundle\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    EzPlatformAdminUiBundle\Controller\DashboardController:
        public: true
        arguments:
            $permissionResolver: '@=service("ezpublish.api.repository").getPermissionResolver()'
            $searchService: '@ezpublish.api.service.search'
            $contentService: '@ezpublish.api.service.content'
            $contentTypeService: '@ezpublish.api.service.content_type'

    EzPlatformAdminUiBundle\Controller\ContentTypeController:
        public: true
        arguments:
            $contentTypeActionDispatcher: '@ezrepoforms.action_dispatcher.content_type'
